name: test coverage
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: yarn install
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./src
